### ISSUE TITLE
missing include

### ISSUE THREAD

**Issue by mrmikeo** [Frog-Coin/Frog-Coin-Core#4]
demimodule.cpp line 7 need to add:

#include <fstream>

**Comment by mrmikeo** [comment]
`#include <fstream>`

**Comment by stfuowned** [comment]
why?

**Comment by mrmikeo** [comment]
Won't build on a default ubuntu 16.04 without it

**Comment by stfuowned** [comment]
please follow the build guide [https://github.com/Frog-Coin/Frog-Coin-Core/blob/main/README.md](url) 
16+ builds work

**Comment by stfuowned** [comment]
> Won't build on a default ubuntu 16.04 without it

https://github.com/Frog-Coin/Frog-Coin-Core/blob/main/README.md

**Comment by mrmikeo** [comment]
i already got it built.  thats what it needed for me.   just letting you know.

**Comment by CryptoCoderz** [comment]
Please follow the guide in the README in the future, it will build on Ubuntu 16+

**Comment by stfuowned** [comment]
I have old and new vps that built the D fine with the instructions provided.

**Comment by dmbcore** [comment]
I also experienced this issue but for Ubuntu 18.04... Seems to be a problem only with some compilers

**Comment by CryptoCoderz** [comment]
reopening temporarily as this has been patched in upcoming commit

**Comment by CryptoCoderz** [comment]
Resolved as of commit: [210c7ad](https://github.com/Frog-Coin/Frog-Coin-Core/commit/210c7ad11b8a6f575798f1619ffd7422087e569e)

Closing issue :)
